{% set name = "cwl2atom" %}

package:
  name: '{{ name|lower }}'
  version: '{{ load_setup_py_data().version }}'

source:
     path: .

build:
  number: 0
  script: python setup.py install
  noarch: python

test:
  imports:
    - tests
  requires:
    - nose
  source_files:
    - tests
  commands:
    - nosetests tests/


requirements:
  host:
    - setuptools

  run:
    - pyyaml
    - jinja2
    - click
    - setuptools

about:
  home: https://github.com/eoepca/
  license: Apache License
  summary: "CWL conversion to Atom for EOEPCA Resource Manager"