{% set name = "cwl2atom" %}

package:
  name: '{{ name|lower }}'
  version: '{{ load_setup_py_data().version }}'

source:
     path: .

build:
  number: 0
  script: python setup.py install
  noarch: python

test:
  requires:
    - nose
  source_files:
    - src/cwl2atom/tests
  commands:
    - nosetests src/cwl2atom/tests/


requirements:
  host:
    - setuptools

  run:
    - setuptools
    - pyyaml
    - jinja2
    - click
    - nose
    - lxml

about:
  home: https://github.com/eoepca/
  license: Apache License
  summary: "CWL conversion to Atom for EOEPCA Resource Manager"